/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : FMC_Config.h
**     Project     : K64F_USB_CDC
**     Processor   : MK64FN1M0VLL12
**     Component   : Init_FMC
**     Version     : Component 01.003, Driver 01.03, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-20, 14:45, # CodeGen: 1
**     Abstract    :
**          This file implements the FMC (FMC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : FMC
**          Device                                         : FMC
**          Access Protection                              : 
**            Master 0                                     : 
**              Prefetch                                   : Enabled
**              Access protection                          : Read-Write
**            Master 1                                     : 
**              Prefetch                                   : Enabled
**              Access protection                          : Read-Write
**            Master 2                                     : 
**              Prefetch                                   : Enabled
**              Access protection                          : Read-Write
**            Master 3                                     : 
**              Prefetch                                   : Disabled
**              Access protection                          : No access
**            Master 4                                     : 
**              Prefetch                                   : Disabled
**              Access protection                          : Read only
**            Master 5                                     : 
**              Prefetch                                   : Disabled
**              Access protection                          : No access
**          Cache settings                                 : 
**            Bank 0                                       : 
**              Cache replacement control                  : Per set across all four ways
**              Data cache                                 : Enabled
**              Instruction cache                          : Enabled
**              Data prefetch                              : Enabled
**              Instruction prefetch                       : Enabled
**              Page buffer                                : Enabled
**            Bank 1                                       : 
**              Data cache                                 : Enabled
**              Instruction cache                          : Enabled
**              Data prefetch                              : Enabled
**              Instruction prefetch                       : Enabled
**              Page buffer                                : Enabled
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void FMC_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file FMC_Config.h                                                  
** @version 01.03
** @brief
**          This file implements the FMC (FMC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup FMC_Config_module FMC_Config module documentation
**  @{
*/         

#ifndef FMC_Config_H_
#define FMC_Config_H_

/* MODULE FMC. */

/* FMC_PFAPR: M5PFD=1,M4PFD=1,M3PFD=1,M2PFD=0,M1PFD=0,M0PFD=0,M5AP=0,M4AP=1,M3AP=0,M2AP=3,M1AP=3,M0AP=3 */
#define FMC_PFAPR_VALUE      0x0038013FU
#define FMC_PFAPR_MASK       0x003F0FFFU
/* FMC_PFB0CR: B0RWSC=3,CLCK_WAY=0,CINV_WAY=0,S_B_INV=0,B0MW=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,CRC=0,B0DCE=1,B0ICE=1,B0DPE=1,B0IPE=1,B0SEBE=1 */
#define FMC_PFB0CR_VALUE     0x3002001FU
/* FMC_PFB1CR: B1RWSC=3,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,B1MW=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,B1DCE=1,B1ICE=1,B1DPE=1,B1IPE=1,B1SEBE=1 */
#define FMC_PFB1CR_VALUE     0x3002001FU

#define FMC_AUTOINIT

/* END FMC. */
#endif /* #ifndef __FMC_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
