/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : usbFmw1.h
**     Project     : K64F_USB_CDC
**     Processor   : MK64FN1M0VLL12
**     Component   : fsl_usb_framework
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-20, 14:45, # CodeGen: 1
**     Contents    :
**         usb_device_init                                 - usb_status usb_device_init(uint8_t controller_id, usb_device_handle * handle);
**         usb_device_postinit                             - usb_status usb_device_postinit(uint8_t controller_id, usb_device_handle handle);
**         usb_device_deinit                               - usb_status usb_device_deinit(usb_device_handle handle);
**         usb_device_recv_data                            - usb_status usb_device_recv_data(usb_device_handle handle, uint8_t ep_num,...
**         usb_device_send_data                            - usb_status usb_device_send_data(usb_device_handle handle, uint8_t ep_num,...
**         usb_device_cancel_transfer                      - usb_status usb_device_cancel_transfer(usb_device_handle handle, uint8_t...
**         usb_device_register_service                     - usb_status usb_device_register_service(usb_device_handle handle, uint8_t...
**         usb_device_unregister_service                   - usb_status usb_device_unregister_service(usb_device_handle handle, uint8_t...
**         usb_device_init_endpoint                        - usb_status usb_device_init_endpoint(usb_device_handle handle, usb_ep_struct_t...
**         usb_device_deinit_endpoint                      - usb_status usb_device_deinit_endpoint(usb_device_handle handle, uint8_t...
**         usb_device_stall_endpoint                       - usb_status usb_device_stall_endpoint(usb_device_handle handle, uint8_t...
**         usb_device_unstall_endpoint                     - usb_status usb_device_unstall_endpoint(usb_device_handle handle, uint8_t...
**         usb_device_register_application_notify          - usb_status usb_device_register_application_notify(usb_device_handle handle,...
**         usb_device_register_vendor_class_request_notify - usb_status usb_device_register_vendor_class_request_notify(usb_device_handle...
**         usb_device_register_desc_request_notify         - usb_status usb_device_register_desc_request_notify(usb_device_handle handle,...
**         usb_device_get_status                           - usb_status usb_device_get_status(usb_device_handle handle, uint8_t component,...
**         usb_device_set_status                           - usb_status usb_device_set_status(usb_device_handle handle, uint8_t component,...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file usbFmw1.h
** @version 01.00
*/         
/*!
**  @addtogroup usbFmw1_module usbFmw1 module documentation
**  @{
*/         
#ifndef __usbFmw1_H
#define __usbFmw1_H

/* MODULE usbFmw1. */

/* Include inherited modules */
#include "osa1.h"
#include "clockMan1.h"
#include "DbgCs1.h"
#include "Cpu.h"
#include "usb.h"
#include "usb_device_stack_interface.h"

/*! @brief USB controller ID */  
#define USBFMW1_USB_CONTROLLER_ID      USB_CONTROLLER_KHCI_0

 
#endif
/* ifndef __usbFmw1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
