/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : usbFmw1_dev_bsp.c
**     Project     : K64F_USB_CDC
**     Processor   : MK64FN1M0VLL12
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-12-20, 14:45, # CodeGen: 1
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file usbFmw1_dev_bsp.c                                                  
** @version 01.00
*/         
/*!
**  @addtogroup usbFmw1_dev_bsp_module usbFmw1_dev_bsp module documentation
**  @{
*/         
#include "adapter.h"
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include "usb_types.h"
#include "usb_misc.h"
#include "usb_error.h"
#include "fsl_device_registers.h"
#include "fsl_clock_manager.h"
#include "fsl_usb_khci_hal.h"
  
#define BSP_USB_INT_LEVEL                (7)


/*FUNCTION*-------------------------------------------------------------------
*
* Function Name    : usbFmw1_dev_soc_init
* Returned Value   : USB status
* Comments         :
*    This function performs BSP-specific I/O initialization related to USB
*
*END*----------------------------------------------------------------------*/
void usbFmw1_dev_soc_init(uint8_t controller_id)
{ 
  /* Disable USB clock gating */
  CLOCK_SYS_DisableUsbfsClock(controller_id);   
  
  /* Clock setting */
  /* Input clock source:      Auto select */
  /* Input clock frequency:   120 MHz */
  /* Input clock multiplier:  2 */
  /* Input clock divider:     5 */
  /* Module clock frequency:  48 MHz */
  CLOCK_SYS_SetUsbfsSrc(controller_id, kClockUsbfsSrcPllFllSel);              
  /* USB clock divider */
  CLOCK_SYS_SetUsbfsDiv(controller_id, 4U, 1U);
  /* Enable USB clock gating */
  CLOCK_SYS_EnableUsbfsClock(controller_id);    
  #if FSL_FEATURE_SIM_OPT_HAS_USB_VOLTAGE_REGULATOR
    /* Enable USB regulator for device */
    SIM_HAL_SetUsbVoltRegulatorWriteCmd((SIM_Type*)(SIM_BASE), TRUE);
    SIM_HAL_SetUsbVoltRegulatorCmd((SIM_Type*)(SIM_BASE), TRUE);
  #endif
  /* Enable MPU clock gating */
  CLOCK_SYS_EnableMpuClock(0);
  /* Disable MPU - all accesses from all bus masters are allowed */
  MPU_CESR = 0x00;  
}

/*FUNCTION*-------------------------------------------------------------------
*
* Function Name    : usbFmw1_soc_get_usb_dev_int_level
* Returned Value   : usb interrupt level
* Comments         :
*    This function return usb interrupt level
*
*END*----------------------------------------------------------------------*/
uint32_t usbFmw1_soc_get_usb_dev_int_level(uint8_t controller_id)
{
  return (uint32_t)BSP_USB_INT_LEVEL;
}


/* END usbFmw1_dev_bsp */   
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
